name: full-check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: sudo apt install libncurses5-dev
    - name: first_build
      run: |
           ./autogen.sh
           ./configure
           make
           sudo make install
